### ISSUE TITLE
Add the ability to change the symbol for the board in the sidebar

### ISSUE THREAD

**Issue by CMaclellan** [greggigon/mpk-desktop-app#10]
It would be good if the symbol for the board in the sidebar used the first letter of the board name.

Optionally, it would be nice to be able to manually set the symbol or to be able to set it as an image.

**Comment by greggigon** [comment]
A very nice suggestion.
I will add this into the backlog.

**Comment by greggigon** [comment]
The board is now using first letter of the board name as the symbol.
@CMaclellan do you think that is good enough ?

**Comment by greggigon** [comment]
Closing the suggestion. Changed to use first letters of the Board name
