### ISSUE TITLE
Regaining focus opens 'NewTask' overlay

### ISSUE THREAD

**Issue by Sh0rxy** [greggigon/mpk-desktop-app#11]
When the window of MPK regains focus it opens the overlay to add a new card by itself.
The same visuals appear as if you hovered on the 'Add new card' button.
After hovering over the button and moving the mouse away it disappears just as expected.

This behavior currently occurs in Kubuntu 20.04.
MPK was installed with the currently downloadable .deb

**Comment by greggigon** [comment]
Hi @Sh0rxy 
I've been trying to recreate your issue and I can't see it in the Beta-0 version on Ubuntu.
Is there a chance you could record a short screen cast and attach/publish somewhere?
I've seen behavior described by you before, while developing on my Mac, but it disappeared some time ago.

**Comment by Sh0rxy** [comment]
https://user-images.githubusercontent.com/47497708/104292973-be1c2600-54bd-11eb-8e9b-6594c68e9077.mp4

Here is a short clip showing what happens. 
As you will see, this will not happen every time. The trigger is clicking the add new card button to hide the overlay after it opened itself. Clicking anywhere after tabbing back-in will restore the normal behavior.

I hope this helps you to narrow down the problem causing code :)

**Comment by greggigon** [comment]
I just managed to reproduce it not only on Ubuntu but on Mac as well. 
Thanks for posting this. I shall investigate.

**Comment by greggigon** [comment]
@Sh0rxy 
I identified the issue in the Material-UI component that I'm using in the app (SpeedDial).
Raised an issue on their project: [https://github.com/mui-org/material-ui/issues/24388](https://github.com/mui-org/material-ui/issues/24388).
Perhaps they will post a workaround or something.

**Comment by greggigon** [comment]
I think it is now resolved. You can test yourself if you clone the latest develop or you can wait for the proper release that should come out in the next few days.
