### ISSUE TITLE
Set tag textcolor

### ISSUE THREAD

**Issue by Sh0rxy** [greggigon/mpk-desktop-app#12]
Choosing a light tag color will make the tag name unreadable in dark mode.
Choosing a dark tag color will make the tag name unreadable in light mode.
Being able to set a custom color for the tag text or set a text color with a higher contrast automatically might help.

**Comment by greggigon** [comment]
Good idea, thanks for the suggestion. Added to backlog.

**Comment by greggigon** [comment]
It's possible now to set the TAG Text color with the new changes
