### ISSUE TITLE
Task list regexes - multiple issues

### ISSUE THREAD

**Issue by raffaelj** [greggigon/mpk-desktop-app#18]
I'm searching for a simple, server-less kanban app for years now. So - many thanks for the effort. I fiddled a bit with the current develop branch and `yarn dev` on my local machine and tried to use/break the task list feature.

## 1. Task lists with asterisk `* [ ] ` aren't recognized

First I thought, it doesn't work at all, because I always use asterisks for list items when writing markdown.

This works:

```
- [ ] task 1
- [x] task 2
```

This doesn't work:

```
* [ ] task 1
* [x] task 2
```

Starting a task list with `-`, `+` and `*` should be valid.

## 2. Regex matches invalid lines

These items are recognized as tasks:

```
*- [ ] zui
-a[ ] 
-[test]test
- [link](url)
```

## 3. Tasks with duplicated names are marked as solved at once

```
List one

- [ ] task 1
- [ ] push to remote

List two

- [ ] task 2
- [ ] push to remote
```

If I click on "push to remote", both items are updated.

## Conclusion/Solution

Two fix **1** and **2**, the regex should look kind of like this `const checkboxRegex = /^[-|+|*] ?\[(.*)\](?:\s)(.*)/gm;` to match valid lines. The replacement in `boardOperations.ts` should also be updated, but it needs a workover anyways because of **3**.

See: https://github.com/greggigon/mpk-desktop-app/blob/develop/app/utils/stringUtils.ts#L7
and: https://github.com/greggigon/mpk-desktop-app/blob/develop/app/features/board/boardOperations.ts#L171

Maybe you should consider using a markdown library like marked or markdown-it to prevent reinventing the wheel with these regex issues.

**Comment by greggigon** [comment]
@raffaelj thank you very much for looking and trying out the app. 
An awesome contribution from you in this issue.  

I was thinking of markdown, library for Description rendering and editing.
The tasks pulled from description are not represented by any specific data model, simply bits of text with a `-[ ]` characters, shown in a friendly way on the card, with possibility of ticking them off.

To fix 1 and 1, you are right, I need a better regex. However, to fix 3, I need to look into representing the tasks as a data modeled a bit more than the Description text is.

**Comment by raffaelj** [comment]
> To fix 1 and 2, you are right, I need a better regex.

In case, you don't know it, https://regex101.com/ is a great resource for regex testing. I made my regex from above over there.

> However, to fix 3, I need to look into representing the tasks as a data modeled a bit more than the Description text is.

Yes. Doing these regex comparisons constantly on a lot of tasks with long texts might also cause some RAM issues sooner or later.

**Comment by greggigon** [comment]
Right, I updated the regex and there is a better handling of the tasks. Now in develop, with #24 .
I think I would like to rethink the lot by introducing Markdown library for more complex scenarios.
For now, if you have multiple list you will need to ensure your tasks does not contain exactly the same content.
I will close this issue and create new one as **enhancement** with proper Markdown handling of the Description.
