### ISSUE TITLE
Rename `app.dat` and `board.dat` to `*.json`

### ISSUE THREAD

**Issue by raffaelj** [greggigon/mpk-desktop-app#20]
The data files are just json files, so they should be named `board.json`. This would help to understand the data structure faster *and* my text editor can detect the syntax highlighting on the fly.

**Comment by greggigon** [comment]
Those are indeed JSON files for now.
When I started I was considering some more performant and compact serialization mechanisms than JSON. That is why the file extension is DAT as the actual format might be something else in the future. Not sure what it would be yet. Was thinking of ProtoBuf, etc. 

Anyways, I use VS Code as my editor and when opening those DAT files, I simply change the Language Mode to JSON.
I did find out that working more on the App, I was opening the files less and less so the DAT extension is not really that annoying.

**Comment by raffaelj** [comment]
> I simply change the Language Mode to JSON

Too many clicks :-)

> Not sure what it would be yet.

If I could make a wish - I would use a folder structure with markdown files with (hidden) yaml frontmatter - synced with a SQLite database in JSON format, (eventually with a MongoLite wrapper). This way, the whole data is portable and syncable. The database can easily be fetched and syncing could be done on startup, periodically or even with a file watcher that triggers a sync if a file changes.

With all data in a single json file I'm a bit afraid of losing all my boards with a single write error.

**Comment by greggigon** [comment]
You are right, it would be better to split into multiple files and build some simple folder structure. As you say, less damage when things go ... awkward 😄 
This would benefit from some deeper thought and a design for the migration from the current to the new shape.
When you mention Markdown, do you mean for the Description field of the card?

**Comment by raffaelj** [comment]
> When you mention Markdown, do you mean for the Description field of the card?

Yes. So `~/configurable_storage_dir/board1/column1/task2.md` could look like this:

```
---
title: update on remotes
tags: ["work","That one project"]
created: '2021-01-12T13:34:31.868Z'
modified: '2021-01-12T13:35:05.593Z'
---

# Commit local changes and push to upstream and origin

Just a *Test*.

* [x] task
* [ ] task 2
```
