### ISSUE TITLE
Too small card when using checklist with multi-line last entry

### ISSUE THREAD

**Issue by antolabbruzzo** [greggigon/mpk-desktop-app#32]
I have a card with a checklist in its description. I found out that when the last entry occupies two or more lines in the Kanban main view (i.e. when the function "Show tasks on cards" is on), the words appear too much close to lower border of the card. Can the latter be stretched down a bit in this case, perhaps?

**Comment by greggigon** [comment]
hi @antolabbruzzo 
Do you think you could attach a screenshot ?

**Comment by antolabbruzzo** [comment]
Sure, here it is.

![screenshot_issue32](https://user-images.githubusercontent.com/45127107/106269500-dd8cb000-622c-11eb-8789-a2d49752a675.png)
