### ISSUE TITLE
Windows binary says update will be applied on exit... repeatedly

### ISSUE THREAD

**Issue by orcpac7** [greggigon/mpk-desktop-app#4]
Great evolution of web-based product, good execution so far. Laudatory comments aside, I just installed from your webpage onto Windows 10 and observe an anomaly.
I realize it's marked as beta, but it displays a message to the effect that it's going to load the next version on exit. Since no matter how many times you exit and come back in it displays, I'm thinking this is a future update capability that doesn't yet detect when there really IS a next version.

![image](https://user-images.githubusercontent.com/1434423/103311790-493eeb80-49e9-11eb-98ac-008afbde1f10.png)

**Comment by greggigon** [comment]
Interesting, I didn't even implement that feature yet 😄 
Must be something that Electron framework comes with. 
Thanks for letting me know. I will fire up the VM and test it myself. Will let you know as soon as the bug is gone.

**Comment by greggigon** [comment]
I removed the auto-updater for now, it requires to be properly implemented in the future.
The binary in the box.com is now also updated. If you re-install and still get the notification, I would be a bit puzzled 😉
