### ISSUE TITLE
Where is the task feature?

### ISSUE THREAD

**Issue by fehivi1010** [greggigon/mpk-desktop-app#42]
### There is a button in the bottom left with the tooltip "show tasks on cards", but where can I set these tasks? Thanks.

**Comment by semagnum** [comment]
There's a video on [this page](https://greggigon.com/my-personal-kanban-2-0/) that helps. If you start a line with "- [] ", then the card will parse that line as a task and show up.
I do agree that it should be more obvious somehow, such as a button to convert between tasks and text (or simply make them separate entries on the card - one input for the description, another for tasks). If I didn't know the feature existed from the video and notes, I would not have figured it out.

**Comment by greggigon** [comment]
Thank you @fehivi1010 for asking the question and for trying out My Personal Kanban.
As @semagnum mentioned, it's in the video and it is -[] , as per Markdown. 
I have a plan to add Help pages to the application very soon.
