### ISSUE TITLE
Problems with Download binaries

### ISSUE THREAD

**Issue by hh65** [greggigon/mpk-desktop-app#52]
Hi,
I would like to use your Kanban board. But I am not able to download the binaries via box via this link from your homepage:
https://app.box.com/s/qavbz3akhooa0u0kxyycvyb3y0ope77l (Windows version) There shows a download button with the size of the binary, but then nothing is downloaded.
Do I miss something?
Thank you for a short info.
Regards
Harald

**Comment by greggigon** [comment]
Hi @hh65 
Thanks for checking out the app.
I just tried to download with the same link and it worked. I did try to download using Safari on Mac and got warned by safari that there is a binary download. 
Perhaps Windows is blocking the exe file for you?

I'm working on making the releases available on GitHub very soon as well as auto-updating function of the application.

**Comment by hh65** [comment]
Thank you for your response. Via Mac and Safari I was able to download the program. Maybe the windows download didn't work, because the windows machine is behind a firewall.
Beside that: very nice app. I like it.
