### ISSUE TITLE
tick-box tasks do not show on cards

### ISSUE THREAD

**Issue by lolavi** [greggigon/mpk-desktop-app#62]
I've just installed mpk on my mac (OS 10.14.6 (18G6020), French keyboard) 

I wanted to use the tick-box task feature, and I think I followed the procedure correctly:
- writing [] in the description
- selecting "show tasks on cards" on the bottom left

The tick boxes are recorded in the description, but do not show on the card in the column.

Can you help with this?

**Comment by semagnum** [comment]
I believe the syntax is "- [] " to have them show up. That's what makes them show up in mine :)

**Comment by lolavi** [comment]
Thanks semagnum, but "- []" doesn't work for me either :-(

Sorry, it actually does!! 
I needed to hide and show again the tasks 

problem solved :-)
many thanks
