### ISSUE TITLE
Standardized ordering of Tags

### ISSUE THREAD

**Issue by Sh0rxy** [greggigon/mpk-desktop-app#9]
A possible feature would be a consistent order in which tags for a task are displayed. Currently if you have 2 or more tags they are ordered by time of selection inside the task.

A unified order will help at distinguishing similar tasks from different ones.

You could for example order them alphabetically or in order of creation of the tags.
Also, if wanted, the possibility to provide a custom sorting is also an option.

**Comment by greggigon** [comment]
Thank you for the great suggestion @Sh0rxy 
I think I will start by simply keeping consistent Alphabetical order.
Goes onto the backlog of improvements.

**Comment by CMaclellan** [comment]
Another possibly sort order that might be useful is would be Tag Usage Count, if a tag is used in many cards have it show first.

The ability to set the priority of tags might be interesting as well, but maybe that is out of scope for how tags should be used.

**Comment by greggigon** [comment]
Ok, deliverd with the PR #16 and will be in the next Milestone release in a few days.
